#!/usr/bin/env bash
#
# https://docs.docker.com/docker-cloud/builds/advanced/

echo '[***] Build hook started'

docker build \
    --build-arg WORDPRESS_TAG="${DOCKER_TAG}" \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" .

echo '[***] Build hook ended'
